### ISSUE TITLE
eos-claimer gets stuck when api error happens

### ISSUE THREAD

**Issue by dfguo** [eoscanada/eos-claimer#1]
every time eos-claimer have an error, it gets stuck on the next call to `ctionResp, err := api.SignPushActions(act)`

**Comment by abourget** [comment]
Thanks Dafeng for the report.

@dfguo spotted an issue in eos-go that made this fail. I'll be rolling out a fixed version with https://github.com/eoscanada/eos-go/commit/ca7795bb92d958e9e44d4c680f493fdedbb8bd42

Ref: https://github.com/eoscanada/eos-go/issues/15

**Comment by abourget** [comment]
https://github.com/eoscanada/eos-claimer/commit/cebfe94cab6650408580036c8c02e24b9a01ae58 imports the latest eos-go lib

**Comment by abourget** [comment]
You can rebuild from source with: `go get -v -u github.com/eoscanada/eos-claimer` .. should all work without a hiccup now. (crossing fingers!)
